Controllers/UserRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Mvc;

namespace Shiksha.Controllers
{
    public class UserRolesController : Controller
    {
        // GET: UserRoles
        public ActionResult UserRolesManagement()
        {
            return View();
        }

        public ActionResult User()
        {
            return View();
        }

        public ActionResult Role()
        {
            return View();
        }

        public ActionResult Permission()
        {
            return View();
        }
        public ActionResult RolePermission()
        {
            return View();
        }
    }
}

Views/UserRoles/Permission.cshtml
@{
    ViewBag.Title = "Permission";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="page">
    <div class="page-wrapper">
        <header class="header ">
            <div class="header-left">
                <a href="" class="logo logo-admin">
                    <img src="../assets/images/admin-logo.svg" />
                </a>
            </div>
            <div class="header-right">
                <div class="download-options header-nav-link html-click">
                    <div class="download-icon">
                        <svg>
                            <use xlink:href="#download" href="#download"></use>
                        </svg>
                    </div>
                    <ul class="menu-actions download-menu-actions">
                        <li href="#" class="menu-item">
                            <a href="#">Desktop</a>
                        </li>
                        <li href="#" class="menu-item">
                            <a href="#">Tablet</a>
                        </li>
                        <li href="#" class="menu-item">
                            <a href="#">Mobile</a>
                        </li>
                    </ul>
                </div>
                <div class="header-nav-link lang-change-icon active">
                    <svg>
                        <use xlink:href="#hindi-lang-toggle" href="#hindi-lang-toggle"></use>
                    </svg>
                    <svg>
                        <use xlink:href="#english-lang-toggle" href="#english-lang-toggle"></use>
                    </svg>
                </div>
                <div class="lms-notification-options header-nav-link html-click">
                    <div class="notifications-icon">
                        <svg>
                            <use xlink:href="#notification" href="#notification"></use>
                        </svg>
                        <div class="notifications-count">3</div>
                    </div>
                    <div class="menu-actions notifications-menu-items">
                        <div class="notifications-menu-items-header lms-side-center-far">
                            <div class="notifications-header">Notifications (2)</div>
                            <div class="lms-clear-all-icon" title="Clear All">
                                <svg>
                                    <use xlink:href="#clear-all" href="#clear-all"></use>
                                </svg>
                            </div>
                        </div>
                        <ul class="notifications-menu-items-list">
                            <li class="menu-item">
                                <a href="#" class="notification-item lms-unread">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-large-img" src="../assets/images/notifications/profile.png" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> Chauhan has raised an IT ticket - SC0824 </div>
                                        <div class="lms-notification-date">8 mins ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/schools-icon.svg" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> The Khaitan school, content updated successfully </div>
                                        <div class="lms-notification-date">1 day ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/upload-to-web.svg" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> Error in downloading content from web </div>
                                        <div class="lms-notification-date">1 day ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item lms-no-notification-image">
                                    <!--<div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/upload-to-web.svg" alt="notification image" />
                                    </div>-->
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> This is one read notifications, which doesn't have any image on the left.. </div>
                                        <div class="lms-notification-date">2 days ago</div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <div class="lms-notification-view-all">
                            <a href="#" class="lms-notification-view-all-link">View All</a>
                        </div>
                    </div>
                </div>
                <div class="header-nav-link profile-section html-click">
                    <div class="profile-img-section">
                        <img class="profile-img" src="../assets/images/avatar.png" />
                    </div>
                    <div class="profile-info-section">
                        <div class="profile-name">Ranveer S</div>
                        <div class="profile-role">admin</div>
                    </div>
                    <div class="profile-more-options-section">
                        <div class="profile-more-option">
                            <svg>
                                <use xlink:href="#dropdown" href="#dropdown"></use>
                            </svg>
                        </div>
                    </div>
                    <ul class="profile-actions menu-actions">
                        <li class="menu-item">
                            <a href="#">Profile</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Settings</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="">
            <div class="page-header">
                <div>
                    <ol class="breadcrumb">
                        <li class="active"><a href="@Url.Action("Dashboard","Home")">Home</a></li>
                        <li class="active"><a href="@Url.Action("UserRolesManagement","UserRoles")">Users and Roles</a></li>
                        <li class="active">Permissions</li>
                    </ol>
                </div>
                <div class="row">
                    <div class="col-xs-10">
                        <h2 class="page-head">Permissions </h2>
                    </div>

                    <div class="col-xs-2">

                    </div>
                </div>

            </div>
            <div class="toggle-col small help-block" id="divToogle">
                Show/Hide columns :
                <a id="t0" class="label label-success" href="javascript:void(0);" onclick="fnShowAll([1,2,3],'permissionTable');">Show All</a>
                <a id="t1" class="label label-success" href="javascript:void(0);"
                   onclick="fnShowHide(1,'permissionTable');">Hierarchy</a>
                <a id="t2" class="label label-success" href="javascript:void(0);"
                   onclick="fnShowHide(2,'permissionTable');">Permission</a>                

            </div>
            <div id="tableDiv">
                <table class="table" id="permissionTable">
                    <thead>
                        <tr class='nosort' style="display: table-row;">
                            <th id="h1" class="nosort" style="width: 40px;">#</th>
                            <th id="h2" class="nosort">Hierarchy</th>
                            <th id="h3" class="nosort">Permission</th>                            
                        </tr>

                    </thead>
                    <tbody>                     
                    </tbody>
                </table>
            </div>
            <br>
        </div>
    </div>
</div>

Views/UserRoles/Role.cshtml
@{
    ViewBag.Title = "Role";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="page">
    <div class="page-wrapper">
        <header class="header ">
            <div class="header-left">
                <a href="" class="logo logo-admin">
                    <img src="../assets/images/admin-logo.svg" />
                </a>
            </div>
            <div class="header-right">
                <div class="download-options header-nav-link html-click">
                    <div class="download-icon">
                        <svg>
                            <use xlink:href="#download" href="#download"></use>
                        </svg>
                    </div>
                    <ul class="menu-actions download-menu-actions">
                        <li href="#" class="menu-item">
                            <a href="#">Desktop</a>
                        </li>
                        <li href="#" class="menu-item">
                            <a href="#">Tablet</a>
                        </li>
                        <li href="#" class="menu-item">
                            <a href="#">Mobile</a>
                        </li>
                    </ul>
                </div>
                <div class="header-nav-link lang-change-icon active">
                    <svg>
                        <use xlink:href="#hindi-lang-toggle" href="#hindi-lang-toggle"></use>
                    </svg>
                    <svg>
                        <use xlink:href="#english-lang-toggle" href="#english-lang-toggle"></use>
                    </svg>
                </div>
                <div class="lms-notification-options header-nav-link html-click">
                    <div class="notifications-icon">
                        <svg>
                            <use xlink:href="#notification" href="#notification"></use>
                        </svg>
                        <div class="notifications-count">3</div>
                    </div>
                    <div class="menu-actions notifications-menu-items">
                        <div class="notifications-menu-items-header lms-side-center-far">
                            <div class="notifications-header">Notifications (2)</div>
                            <div class="lms-clear-all-icon" title="Clear All">
                                <svg>
                                    <use xlink:href="#clear-all" href="#clear-all"></use>
                                </svg>
                            </div>
                        </div>
                        <ul class="notifications-menu-items-list">
                            <li class="menu-item">
                                <a href="#" class="notification-item lms-unread">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-large-img" src="../assets/images/notifications/profile.png" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> Chauhan has raised an IT ticket - SC0824 </div>
                                        <div class="lms-notification-date">8 mins ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/schools-icon.svg" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> The Khaitan school, content updated successfully </div>
                                        <div class="lms-notification-date">1 day ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/upload-to-web.svg" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> Error in downloading content from web </div>
                                        <div class="lms-notification-date">1 day ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item lms-no-notification-image">
                                    <!--<div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/upload-to-web.svg" alt="notification image" />
                                    </div>-->
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> This is one read notifications, which doesn't have any image on the left.. </div>
                                        <div class="lms-notification-date">2 days ago</div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <div class="lms-notification-view-all">
                            <a href="#" class="lms-notification-view-all-link">View All</a>
                        </div>
                    </div>
                </div>
                <div class="header-nav-link profile-section html-click">
                    <div class="profile-img-section">
                        <img class="profile-img" src="../assets/images/avatar.png" />
                    </div>
                    <div class="profile-info-section">
                        <div class="profile-name">Ranveer S</div>
                        <div class="profile-role">admin</div>
                    </div>
                    <div class="profile-more-options-section">
                        <div class="profile-more-option">
                            <svg>
                                <use xlink:href="#dropdown" href="#dropdown"></use>
                            </svg>
                        </div>
                    </div>
                    <ul class="profile-actions menu-actions">
                        <li class="menu-item">
                            <a href="#">Profile</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Settings</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="">
            <div class="page-header">
                <div>
                    <ol class="breadcrumb">
                        <li class="active"><a href="@Url.Action("Dashboard","Home")">Home</a></li>
                        <li class="active"><a href="@Url.Action("UserRolesManagement","UserRoles")">Users and Roles</a></li>
                        <li class="active">Existing Roles</li>
                    </ol>
                </div>
                <div class="row">
                    <div class="col-xs-10">
                        <h2 class="page-head">Existing Roles</h2>
                    </div>

                    <div class="col-xs-2">
                            <a class="create-items-section pull-right lms-add-btn" onclick="initInput();fnInitSaveAndAddNewList();" data-toggle="modal">
                                <div class="create-item-icon">
                                    <svg>
                                        <use xlink:href="web-resources/images/projects.svg#add" href="web-resources/images/projects.svg#add"></use>
                                    </svg>
                                </div>
                                <div class="create-item-text action-text"><spring:message code="role.add" text="Add Role" /></div>
                            </a>
                    </div>
                </div>

            </div>
            <div class="toggle-col small help-block" id="divToogle">
                Show/Hide columns :
                <a id="t0" class="label label-success" href="javascript:void(0);" onclick="fnShowAll([1,2,3,4,5],'roleTable');">Show All</a>
                <a id="t1" class="label label-success" href="javascript:void(0);" onclick="fnShowHide(1,'roleTable');">Role</a>
                <a id="t2" class="label label-success" href="javascript:void(0);" onclick="fnShowHide(2,'roleTable');">Role Acronym</a>
                <a id="t3" class="label label-success" href="javascript:void(0);" onclick="fnShowHide(3,'roleTable');">Sequence Number</a>
                <a id="t4" class="label label-success" href="javascript:void(0);" onclick="fnShowHide(4,'roleTable');">Application</a>
                <a id="t5" class="label label-success" href="javascript:void(0);" onclick="fnShowHide(5,'roleTable');">Mapped To School</a>
            </div>
            <div id="tableDiv">
                <table class="table" id="roleTable">
                    <thead>
                        <tr id="head">
                            <th id="h1" class="nosort" style="width: 40px">#</th>
                            <th id="h2" class="nosort">Role</th>
                            <th id="h3" class="nosort">Role Acronym</th>
                            <th id="h4" class="nosort">Sequence Number</th>

                            <th id="h5" class="nosort">Application</th>


                            <th id="h6" class="nosort">Mapped To School</th>
                            <th id="h7" class="nosort" style="width: 60px">Action</th>
                        </tr>

                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
            </div>
            <br>
        </div>

    </div>
</div>