Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Mvc;

namespace Shiksha.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Student()
        {
            return View();
        }
        public ActionResult BulkUpload()
        {
            return View();
        }
    }
}

Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Mvc;

namespace Shiksha.Controllers
{
    public class TeacherController : Controller
    {
        // GET: Teacher
        public ActionResult Teacher()
        {
            return View();
        }
        public ActionResult BulkUpload()
        {
            return View();
        }
    }
}

Controllers/TeachingPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Mvc;

namespace Shiksha.Controllers
{
    public class TeachingPlanController : Controller
    {
        // GET: TeachingPlan
        public ActionResult TeachingPlanGradeSectionMapping()
        {
            return View();
        }
    }
}

Controllers/UtilitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Mvc;

namespace Shiksha.Controllers
{
    public class UtilitiesController : Controller
    {
        // GET: Utilities
        public ActionResult utilities()
        {
            return View();
        }
        public ActionResult UpgradeAcademicYear()
        {
            return View();
        }
        public ActionResult Holiday()
        {
            return View();
        }
        public ActionResult AppDownload()
        {
            return View();
        }
    }
}

Views/Utilities/AppDownload.cshtml
@{
    ViewBag.Title = "AppDownload";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>AppDownload</h2>

Views/Utilities/Holiday.cshtml
@{
    ViewBag.Title = "Holiday";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="page">
    <div class="page-wrapper">
        <header class="header ">
            <div class="header-left">
                <a href="" class="logo logo-admin">
                    <img src="../assets/images/admin-logo.svg" />
                </a>
            </div>
            <div class="header-right">
                <div class="download-options header-nav-link html-click">
                    <div class="download-icon">
                        <svg>
                            <use xlink:href="#download" href="#download"></use>
                        </svg>
                    </div>
                    <ul class="menu-actions download-menu-actions">
                        <li href="#" class="menu-item">
                            <a href="#">Desktop</a>
                        </li>
                        <li href="#" class="menu-item">
                            <a href="#">Tablet</a>
                        </li>
                        <li href="#" class="menu-item">
                            <a href="#">Mobile</a>
                        </li>
                    </ul>
                </div>
                <div class="header-nav-link lang-change-icon active">
                    <svg>
                        <use xlink:href="#hindi-lang-toggle" href="#hindi-lang-toggle"></use>
                    </svg>
                    <svg>
                        <use xlink:href="#english-lang-toggle" href="#english-lang-toggle"></use>
                    </svg>
                </div>
                <div class="lms-notification-options header-nav-link html-click">
                    <div class="notifications-icon">
                        <svg>
                            <use xlink:href="#notification" href="#notification"></use>
                        </svg>
                        <div class="notifications-count">3</div>
                    </div>
                    <div class="menu-actions notifications-menu-items">
                        <div class="notifications-menu-items-header lms-side-center-far">
                            <div class="notifications-header">Notifications (2)</div>
                            <div class="lms-clear-all-icon" title="Clear All">
                                <svg>
                                    <use xlink:href="#clear-all" href="#clear-all"></use>
                                </svg>
                            </div>
                        </div>
                        <ul class="notifications-menu-items-list">
                            <li class="menu-item">
                                <a href="#" class="notification-item lms-unread">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-large-img" src="../assets/images/notifications/profile.png" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> Chauhan has raised an IT ticket - SC0824 </div>
                                        <div class="lms-notification-date">8 mins ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/schools-icon.svg" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> The Khaitan school, content updated successfully </div>
                                        <div class="lms-notification-date">1 day ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/upload-to-web.svg" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> Error in downloading content from web </div>
                                        <div class="lms-notification-date">1 day ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item lms-no-notification-image">
                                    <!--<div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/upload-to-web.svg" alt="notification image" />
                                    </div>-->
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> This is one read notifications, which doesn't have any image on the left.. </div>
                                        <div class="lms-notification-date">2 days ago</div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <div class="lms-notification-view-all">
                            <a href="#" class="lms-notification-view-all-link">View All</a>
                        </div>
                    </div>
                </div>
                <div class="header-nav-link profile-section html-click">
                    <div class="profile-img-section">
                        <img class="profile-img" src="../assets/images/avatar.png" />
                    </div>
                    <div class="profile-info-section">
                        <div class="profile-name">Ranveer S</div>
                        <div class="profile-role">admin</div>
                    </div>
                    <div class="profile-more-options-section">
                        <div class="profile-more-option">
                            <svg>
                                <use xlink:href="#dropdown" href="#dropdown"></use>
                            </svg>
                        </div>
                    </div>
                    <ul class="profile-actions menu-actions">
                        <li class="menu-item">
                            <a href="#">Profile</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Settings</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>

        <div class="">
            <div class="page-header noborder">
                <div>
                    <ol class="breadcrumb">
                        <li class="active"><a href="@Url.Action("Dashboard", "Home")">Home</a></li>
                        <li class="active"><a href="@Url.Action("Utilities", "Utilities")">Utilities</a></li>
                        <li class="active"><spring:message code="app.menu.holiday" text="Holidays" /></li>
                    </ol>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <h2 class="page-head"><spring:message code="app.menu.holiday" text="Holidays" /></h2>
                    </div>

                    <div class="col-xs-4">
                        <security:authorize ifAnyGranted="PERMISSION_addShikshaHoliday">
                            <a class="create-items-section pull-right" id="addHoliday">
                                <div class="create-item-icon">
                                    <svg>
                                        <use xlink:href="../assets/images/projects.svg#add" href="../assets/images/projects.svg#add"></use>
                                    </svg>
                                </div>
                                <div class="create-item-text action-text"><spring:message code="holiday.add" text="Add Holiday" /></div>
                            </a>
                        </security:authorize>
                    </div>
                </div>

            </div>

            <div class="filter-contianer" id="toolbarHoliday" style="display:none;">
                <div class="form-group ">
                    <select onchange="holiday.getDataByYear()"
                            data-title="Year" id="selectYear" name="year" class="selectpicker">                    
                    </select>
                </div>
            </div>

            <div id="tableDiv" class="bootstrap-table-custom">
                <table class="aui"
                       id="holidayTable" data-toolbar="#toolbarHoliday" data-unique-id="id">
                    <thead>
                        <tr id="head">

                            <th data-field="name"><spring:message code="holiday.name" text="Name" /></th>
                            <th data-field="startDate"><spring:message code="holiday.startDate" text="Start Date" /></th>
                            <th data-field="endDate"><spring:message code="holiday.endDate" text="End Date" /></th>
                            <th data-field="totalNoOfDays"><spring:message code="holiday.noOfDays" text="No of days" /></th>
                            <th data-formatter="holiday.holidayActionFormater"
                                class="td-actions text-center action-container tooltip-visible" data-cell-style="holidayFilter.actionFormater"
                                data-width="60px">
                                <spring:message code="holiday.action" text="Action" />
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>






    </div>
</div>

Views/Utilities/utilities.cshtml
@{
    ViewBag.Title = "utilities";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<div class="page">
    <div class="page-wrapper">
        <header class="header ">
            <div class="header-left">
                <a href="" class="logo logo-admin">
                    <img src="../assets/images/admin-logo.svg" />
                </a>
            </div>
            <div class="header-right">
                <div class="download-options header-nav-link html-click">
                    <div class="download-icon">
                        <svg>
                            <use xlink:href="#download" href="#download"></use>
                        </svg>
                    </div>
                    <ul class="menu-actions download-menu-actions">
                        <li href="#" class="menu-item">
                            <a href="#">Desktop</a>
                        </li>
                        <li href="#" class="menu-item">
                            <a href="#">Tablet</a>
                        </li>
                        <li href="#" class="menu-item">
                            <a href="#">Mobile</a>
                        </li>
                    </ul>
                </div>
                <div class="header-nav-link lang-change-icon active">
                    <svg>
                        <use xlink:href="#hindi-lang-toggle" href="#hindi-lang-toggle"></use>
                    </svg>
                    <svg>
                        <use xlink:href="#english-lang-toggle" href="#english-lang-toggle"></use>
                    </svg>
                </div>
                <div class="lms-notification-options header-nav-link html-click">
                    <div class="notifications-icon">
                        <svg>
                            <use xlink:href="#notification" href="#notification"></use>
                        </svg>
                        <div class="notifications-count">3</div>
                    </div>
                    <div class="menu-actions notifications-menu-items">
                        <div class="notifications-menu-items-header lms-side-center-far">
                            <div class="notifications-header">Notifications (2)</div>
                            <div class="lms-clear-all-icon" title="Clear All">
                                <svg>
                                    <use xlink:href="#clear-all" href="#clear-all"></use>
                                </svg>
                            </div>
                        </div>
                        <ul class="notifications-menu-items-list">
                            <li class="menu-item">
                                <a href="#" class="notification-item lms-unread">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-large-img" src="../assets/images/notifications/profile.png" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> Chauhan has raised an IT ticket - SC0824 </div>
                                        <div class="lms-notification-date">8 mins ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/schools-icon.svg" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> The Khaitan school, content updated successfully </div>
                                        <div class="lms-notification-date">1 day ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item">
                                    <div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/upload-to-web.svg" alt="notification image" />
                                    </div>
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> Error in downloading content from web </div>
                                        <div class="lms-notification-date">1 day ago</div>
                                    </div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="notification-item lms-no-notification-image">
                                    <!--<div class="lms-notification-img">
                                        <img class="lms-notification-small-img" src="../assets//images/notifications/upload-to-web.svg" alt="notification image" />
                                    </div>-->
                                    <div class="lms-notification-detail-section">
                                        <div class="lms-notification-detail"> This is one read notifications, which doesn't have any image on the left.. </div>
                                        <div class="lms-notification-date">2 days ago</div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <div class="lms-notification-view-all">
                            <a href="#" class="lms-notification-view-all-link">View All</a>
                        </div>
                    </div>
                </div>
                <div class="header-nav-link profile-section html-click">
                    <div class="profile-img-section">
                        <img class="profile-img" src="../assets/images/avatar.png" />
                    </div>
                    <div class="profile-info-section">
                        <div class="profile-name">Ranveer S</div>
                        <div class="profile-role">admin</div>
                    </div>
                    <div class="profile-more-options-section">
                        <div class="profile-more-option">
                            <svg>
                                <use xlink:href="#dropdown" href="#dropdown"></use>
                            </svg>
                        </div>
                    </div>
                    <ul class="profile-actions menu-actions">
                        <li class="menu-item">
                            <a href="#">Profile</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Settings</a>
                        </li>
                        <li class="menu-item">
                            <a href="#">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        <main class="main-content top-shade">
            <div>
                <ol class="breadcrumb">
                    <li class="active"><a href="@Url.Action("Dashboard", "Home")">Home</a></li>
                    <li class="active">Utilities</li>
                </ol>
            </div>
            <div class="lms-heading-section">
                <div class="heading-left">
                    <a href="home" class="back-nav">
                        <svg>
                            <use xlink:href="../assets/images/common.svg#back" href="../assets/images/common.svg#back"></use>
                        </svg>
                    </a>
                    <div class="sub-heading items-heading">Utilities</div>
                </div>
            </div>
            <div class="overview-cards clrflt utilities-menu" style="margin-top:15px">


                <a href="@Url.Action("UpgradeAcademicYear", "Utilities")" class="overview-card utilities-card">
                    <div class="overview-icon locations-icon">
                        <svg>
                            <use xlink:href="../assets/images/icons/utilities-menu.svg#academic-year" href="../assets/images/icons/utilities-menu.svg#academic-year"></use>
                        </svg>
                    </div>
                    <div class="overview-bottom">
                        <div class="overview-card-name">Upgrade to next academic year</div>
                    </div>
                </a>

                <a href="@Url.Action("TeachingPlanGradeSectionMapping", "TeachingPlan")" class="overview-card utilities-card">
                    <div class="overview-icon locations-icon">
                        <svg>
                            <use xlink:href="../assets/images/icons/utilities-menu.svg#Teaching-Plan-Grade-Section-Mapping" href="../assets/images/icons/utilities-menu.svg#Teaching-Plan-Grade-Section-Mapping"></use>
                        </svg>
                    </div>
                    <div class="overview-bottom">
                        <div class="overview-card-name">Teaching Plan Grade Section Mapping</div>
                    </div>
                </a>

                <a href="@Url.Action("Holiday", "Utilities")" class="overview-card utilities-card">
                    <div class="overview-icon locations-icon">
                        <svg>
                            <use xlink:href="../assets/images/icons/utilities-menu.svg#holiday" href="../assets/images/icons/utilities-menu.svg#holiday"></use>
                        </svg>
                    </div>
                    <div class="overview-bottom">
                        <div class="overview-card-name">Holiday</div>
                    </div>
                </a>


                <a href="@Url.Action("BulkUpload", "Teacher")" class="overview-card utilities-card">
                    <div class="overview-icon locations-icon">
                        <svg>
                            <use xlink:href="../assets/images/icons/utilities-menu.svg#bulk-teacher-upload" href="../assets/images/icons/utilities-menu.svg#bulk-teacher-upload"></use>
                        </svg>
                    </div>
                    <div class="overview-bottom">
                        <div class="overview-card-name">Bulk teacher upload</div>
                    </div>
                </a>

                <a href="@Url.Action("BulkUpload", "Student")" class="overview-card utilities-card">
                    <div class="overview-icon locations-icon">
                        <svg>
                            <use xlink:href="../assets/images/icons/utilities-menu.svg#bulk-student-upload" href="../assets/images/icons/utilities-menu.svg#bulk-student-upload"></use>
                        </svg>
                    </div>
                    <div class="overview-bottom">
                        <div class="overview-card-name">Bulk student upload</div>
                    </div>
                </a>



                <a onclick="fnAppDownload();" class="overview-card utilities-card" style="cursor: pointer;">
                    <div class="overview-icon locations-icon">
                        <svg>
                            <use xlink:href="../assets/images/all.svg#download" href="../assets/images/all.svg#download"></use>
                        </svg>
                    </div>
                    <div class="overview-bottom">
                        <div class="overview-card-name">App Download</div>
                    </div>
                </a>

            </div>
        </main>
    </div>
</div>